# generated by datamodel-codegen:
#   filename:  schemas/

from __future__ import annotations

from enum import StrEnum
from typing import Annotated, Any, Literal

from platform_contracts._base import ContractBase
from pydantic import AwareDatetime, ConfigDict, EmailStr, Field

class SigningAlgorithm(StrEnum):
    RSASSA_PKCS1_V1_5_SHA_256 = 'RSASSA_PKCS1_V1_5_SHA_256'
    ECDSA_SHA_384 = 'ECDSA_SHA_384'

class SubjectType(StrEnum):
    package = 'package'
    pipeline = 'pipeline'

class ManifestEnvelope(ContractBase):
    model_config = ConfigDict(
        extra='forbid',
    )
    digest: Annotated[str, Field(pattern='^[0-9a-f]{64}$')]
    digest_algorithm: Literal['SHA-256']
    signature: Annotated[str, Field(min_length=1)]
    signing_key_arn: Annotated[str, Field(pattern='^arn:aws:kms:')]
    signing_algorithm: SigningAlgorithm
    subject_type: SubjectType
    subject_ref: Annotated[str, Field(min_length=1)]
    signed_at: AwareDatetime
    signer_principal: Annotated[str, Field(min_length=1)]
    payload: dict[str, Any]

class ExecutionTier(StrEnum):
    standard = 'standard'
    scalable = 'scalable'

class ModelClass(StrEnum):
    credit = 'credit'
    fraud = 'fraud'
    propensity = 'propensity'
    other = 'other'

class UpstreamPackage(ContractBase):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: Annotated[str, Field(pattern='^[a-z][a-z0-9-]{2,63}$')]
    version: Annotated[str, Field(pattern='^\\d+\\.\\d+\\.\\d+$')]

class ModelConfig(ContractBase):
    model_config = ConfigDict(
        extra='forbid',
    )
    model_name: Annotated[str, Field(pattern='^[a-z][a-z0-9-]{2,63}$')]
    version: Annotated[str, Field(pattern='^\\d+\\.\\d+\\.\\d+$')]
    execution_tier: ExecutionTier
    schedule_cadence: Annotated[str, Field(min_length=1)]
    input_schema_ref: Annotated[str, Field(pattern='^s3://')]
    output_schema_ref: Annotated[str, Field(pattern='^s3://')]
    pir_doc_ref: Annotated[str, Field(pattern='^s3://')]
    owner_email: EmailStr
    accountable_executive: Annotated[str, Field(min_length=1)]
    sla_seconds: Annotated[int, Field(gt=0)]
    model_class: ModelClass | None = None
    registry_lookup_key: str | None = None
    sas_code_version: Annotated[str | None, Field(min_length=1)] = None
    inference_code_version: Annotated[str | None, Field(min_length=1)] = None
    upstream_package: Annotated[
        UpstreamPackage | None,
        Field(
            description='Code Intake package this pipeline scores from. When set, the generator embeds an upstream_refs entry in the pipeline manifest.'
        ),
    ] = None

class Check(ContractBase):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str
    passed: bool
    finding_count: Annotated[int, Field(ge=0)]
    codes: list[str] | None = None

class ValidationSummary(ContractBase):
    model_config = ConfigDict(
        extra='forbid',
    )
    ran_at: AwareDatetime
    checks: list[Check]

class FileRef(ContractBase):
    model_config = ConfigDict(
        extra='forbid',
    )
    path: Annotated[str, Field(min_length=1)]
    sha256: Annotated[str, Field(pattern='^[a-f0-9]{64}$')]

class PackageLayout(ContractBase):
    model_config = ConfigDict(
        extra='forbid',
    )
    sas_files: list[FileRef]
    python_files: list[FileRef]
    test_files: list[FileRef]
    pir_ref: FileRef
    model_config_ref: FileRef

class PackageManifestPayload(ContractBase):
    model_config = ConfigDict(
        extra='forbid',
    )
    schema_version: Literal[1]
    code_intake_version: Annotated[str, Field(pattern='^\\d+\\.\\d+\\.\\d+$')]
    model_name: Annotated[str, Field(pattern='^[a-z][a-z0-9-]{2,63}$')]
    version: Annotated[str, Field(pattern='^\\d+\\.\\d+\\.\\d+$')]
    generated_at: AwareDatetime
    package_layout: PackageLayout
    validation_summary: ValidationSummary

class Tier(StrEnum):
    standard = 'standard'
    scalable = 'scalable'

class ArtifactHashes(ContractBase):
    model_config = ConfigDict(
        extra='forbid',
    )
    statemachine_sha256: Annotated[str, Field(pattern='^[0-9a-f]{64}$')]
    terraform_sha256: Annotated[str, Field(pattern='^[0-9a-f]{64}$')]
    model_config_sha256: Annotated[str, Field(pattern='^[0-9a-f]{64}$')]
    registration_sha256: Annotated[str, Field(pattern='^[0-9a-f]{64}$')]

class UpstreamRefType(StrEnum):
    package = 'package'

class UpstreamRef(ContractBase):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: UpstreamRefType
    ref: Annotated[str, Field(min_length=1)]
    digest: Annotated[str, Field(pattern='^[a-f0-9]{64}$')]

class PipelineManifestPayload(ContractBase):
    model_config = ConfigDict(
        extra='forbid',
    )
    schema_version: Literal[1]
    generator_version: Annotated[str, Field(pattern='^\\d+\\.\\d+\\.\\d+$')]
    model_name: Annotated[str, Field(pattern='^[a-z][a-z0-9-]{2,63}$')]
    version: Annotated[str, Field(pattern='^\\d+\\.\\d+\\.\\d+$')]
    tier: Tier
    generated_at: AwareDatetime
    artifact_hashes: ArtifactHashes
    upstream_refs: Annotated[
        list[UpstreamRef] | None,
        Field(
            description="Chain-of-custody links to upstream manifests. The pipeline's signature covers this array.",
            validate_default=True,
        ),
    ] = []

class PirDataType(StrEnum):
    string = 'string'
    int = 'int'
    float = 'float'
    bool = 'bool'
    date = 'date'
    datetime = 'datetime'
    decimal = 'decimal'

class PirInput(ContractBase):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: Annotated[str, Field(pattern='^[a-z][a-z0-9_]*$')]
    type: PirDataType
    source: Annotated[str, Field(min_length=1)]
    description: str | None = None
    nullable: bool | None = False

class PirOutput(ContractBase):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: Annotated[str, Field(pattern='^[a-z][a-z0-9_]*$')]
    type: PirDataType
    description: str | None = None

class PirMapping(ContractBase):
    model_config = ConfigDict(
        extra='forbid',
    )
    mapping_version: Literal[1]
    model_name: Annotated[str, Field(pattern='^[a-z][a-z0-9-]{2,63}$')]
    model_version: Annotated[str, Field(pattern='^\\d+\\.\\d+\\.\\d+$')]
    inputs: list[PirInput]
    outputs: list[PirOutput]
    notes: str | None = None

class ApprovalStatus(StrEnum):
    pending = 'pending'
    approved = 'approved'
    retired = 'retired'

class RegistryRecord(ContractBase):
    model_config = ConfigDict(
        extra='forbid',
    )
    model_name: Annotated[str, Field(pattern='^[a-z][a-z0-9-]{2,63}$')]
    version: Annotated[str, Field(pattern='^\\d+\\.\\d+\\.\\d+$')]
    sas_code_version: Annotated[str, Field(min_length=1)]
    inference_code_version: Annotated[str, Field(min_length=1)]
    schedule_cadence: Annotated[str, Field(min_length=1)]
    execution_tier: ExecutionTier
    input_schema_ref: Annotated[str, Field(pattern='^s3://')]
    output_schema_ref: Annotated[str, Field(pattern='^s3://')]
    pir_doc_ref: Annotated[str, Field(pattern='^s3://')]
    owner_email: EmailStr
    accountable_executive: Annotated[str, Field(min_length=1)]
    approval_status: ApprovalStatus
    sla_seconds: Annotated[int, Field(gt=0)]
    cab_record_id: str | None = None
    ivu_evidence_ref: Annotated[str | None, Field(pattern='^s3://')] = None
    created_at: AwareDatetime
    updated_at: AwareDatetime
    last_scored_at: AwareDatetime | None = None
    rev: Annotated[int, Field(ge=0)]
