#!/usr/bin/env bash
# Regenerate platform_contracts/models.py from the three canonical JSON Schemas.
# The output is committed; CI will re-run this script and fail on any git diff.
#
# datamodel-codegen 0.58+ requires a directory output for multi-file inputs.
# We work around this by generating each schema to a separate temp file and
# then merging them with deduplication via a Python AST helper.
set -euo pipefail
cd "$(dirname "$0")"

SCHEMAS_DIR="src/platform_contracts/schemas"
OUT="src/platform_contracts/models.py"
TMPDIR="$(mktemp -d)"
trap 'rm -rf "$TMPDIR"' EXIT

# --- Generate each schema individually so the output is a plain .py file ---
SCHEMAS=(
  "manifest-envelope.schema.json"
  "model-config.schema.json"
  "package-manifest-payload.schema.json"
  "pipeline-manifest-payload.schema.json"
  "pir-mapping.schema.json"
  "registry-record.schema.json"
)

for schema in "${SCHEMAS[@]}"; do
  name="${schema%.schema.json}"
  uv run datamodel-codegen \
    --input "${SCHEMAS_DIR}/${schema}" \
    --input-file-type jsonschema \
    --output "${TMPDIR}/${name}.py" \
    --output-model-type pydantic_v2.BaseModel \
    --base-class platform_contracts._base.ContractBase \
    --use-standard-collections \
    --use-union-operator \
    --use-annotated \
    --field-constraints \
    --target-python-version 3.12 \
    --disable-timestamp
done

# --- Merge the three files into one using AST-based deduplication ---
uv run python - "${TMPDIR}" "${OUT}" << 'PYEOF'
import sys
import ast
import re
from pathlib import Path

src_dir = Path(sys.argv[1])
out_path = Path(sys.argv[2])

# Process in deterministic (alphabetical) order derived from generated files
files = sorted(src_dir.glob("*.py"))

# Track what we've seen
seen_class_names: set[str] = set()
seen_future_imports: set[str] = set()
seen_imports: dict[str, set[str]] = {}  # module -> set of names

all_class_blocks: list[str] = []  # raw source text for each class/enum block

for fpath in files:
    text = fpath.read_text(encoding="utf-8")
    tree = ast.parse(text)
    lines = text.splitlines()

    for node in tree.body:
        if isinstance(node, ast.ImportFrom):
            if node.module == "__future__":
                for alias in node.names:
                    seen_future_imports.add(alias.name)
            else:
                module = node.module or ""
                if module not in seen_imports:
                    seen_imports[module] = set()
                for alias in node.names:
                    seen_imports[module].add(alias.name)
        elif isinstance(node, ast.Import):
            raise RuntimeError(f"Unexpected bare 'import' in {fpath}: {ast.dump(node)} — update the merger.")
        elif isinstance(node, ast.ClassDef):
            name = node.name
            if name in seen_class_names:
                continue
            seen_class_names.add(name)
            start = node.lineno - 1
            end = node.end_lineno
            class_src = "\n".join(lines[start:end])
            all_class_blocks.append(class_src)

# Build the output file
out_parts: list[str] = []
out_parts.append("# generated by datamodel-codegen:")
out_parts.append("#   filename:  schemas/")
out_parts.append("")

# from __future__ import annotations
out_parts.append(f"from __future__ import {', '.join(sorted(seen_future_imports))}")
out_parts.append("")

# stdlib imports (non-pydantic, non-platform_contracts)
stdlib_modules = sorted(
    k for k in seen_imports
    if not k.startswith("pydantic") and not k.startswith("platform_contracts")
)
if stdlib_modules:
    for mod in stdlib_modules:
        names = ", ".join(sorted(seen_imports[mod]))
        out_parts.append(f"from {mod} import {names}")
    out_parts.append("")

# third-party imports: platform_contracts first, then pydantic
tp_modules = sorted(
    k for k in seen_imports
    if k.startswith("platform_contracts") or k.startswith("pydantic")
)
if tp_modules:
    for mod in tp_modules:
        names = ", ".join(sorted(seen_imports[mod]))
        out_parts.append(f"from {mod} import {names}")
    out_parts.append("")

# Class definitions separated by blank lines
for block in all_class_blocks:
    out_parts.append("")
    out_parts.append(block)
    out_parts.append("")

# Normalise: no more than 2 consecutive blank lines, trailing newline
result = "\n".join(out_parts)
result = re.sub(r"\n{3,}", "\n\n", result)
if not result.endswith("\n"):
    result += "\n"

out_path.write_text(result, encoding="utf-8")
print(f"Written: {out_path}")
PYEOF
