"""Structured stdout + Markdown report writer for the demo orchestrator.

Uses stdlib ANSI escape codes — no ``rich``, no ``loguru`` dependency. The
Markdown writer produces an artifact suitable for CI upload and for
committing under ``docs/runbooks/sample-transcripts/``.
"""

from __future__ import annotations

import sys
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Literal

AccountLabel = Literal["exl-prod-sim", "absa-sim", "demo"]


@dataclass(frozen=True)
class _Entry:
    """One line of the transcript."""

    account: AccountLabel | str
    message: str
    timestamp_s: float
    duration_s: float | None = None
    failed: bool = False
    exit_code: int | None = None


class Transcript:
    """Append-only structured log with terminal + Markdown sinks."""

    _COLORS = {
        "exl-prod-sim": "\x1b[36m",  # cyan
        "absa-sim": "\x1b[35m",  # magenta
        "demo": "\x1b[33m",  # yellow
        "fail": "\x1b[31m",  # red
        "reset": "\x1b[0m",
    }

    def __init__(self, *, use_color: bool = True) -> None:
        self.use_color = use_color
        self._entries: list[_Entry] = []
        self._start_monotonic = time.monotonic()

    def _t(self) -> float:
        return time.monotonic() - self._start_monotonic

    def demo(self, message: str) -> None:
        entry = _Entry(account="demo", message=message, timestamp_s=self._t())
        self._entries.append(entry)
        self._emit(entry)

    def step(
        self,
        account: AccountLabel | str,
        message: str,
        *,
        duration_s: float | None = None,
    ) -> None:
        entry = _Entry(
            account=account,
            message=message,
            timestamp_s=self._t(),
            duration_s=duration_s,
        )
        self._entries.append(entry)
        self._emit(entry)

    def step_failed(
        self,
        account: AccountLabel | str,
        message: str,
        *,
        exit_code: int,
        duration_s: float | None = None,
    ) -> None:
        entry = _Entry(
            account=account,
            message=message,
            timestamp_s=self._t(),
            duration_s=duration_s,
            failed=True,
            exit_code=exit_code,
        )
        self._entries.append(entry)
        self._emit(entry)

    def _emit(self, entry: _Entry) -> None:
        prefix = f"[{entry.account}]"
        marker = "X FAIL " if entry.failed else "  "
        dur = f"  ({entry.duration_s:.2f}s)" if entry.duration_s is not None else ""
        line = f"{prefix:<18} {marker}{entry.message}{dur}"
        if entry.failed and entry.exit_code is not None:
            line += f"  [exit={entry.exit_code}]"
        if self.use_color:
            color = self._COLORS["fail"] if entry.failed else self._COLORS.get(entry.account, "")
            reset = self._COLORS["reset"]
            line = f"{color}{line}{reset}"
        print(line, file=sys.stdout, flush=True)

    def write_markdown(self, path: Path) -> None:
        lines: list[str] = [
            "# Demo Transcript",
            "",
            f"Generated by `scripts/demo`. Total entries: {len(self._entries)}.",
            "",
            "| t (s) | account | message | duration | result |",
            "|-------|---------|---------|----------|--------|",
        ]
        for e in self._entries:
            dur = f"{e.duration_s:.2f}s" if e.duration_s is not None else ""
            result = f"FAIL exit={e.exit_code}" if e.failed else "ok"
            lines.append(
                f"| {e.timestamp_s:.2f} | [{e.account}] | {e.message} | {dur} | {result} |"
            )
        lines.append("")
        path.write_text("\n".join(lines) + "\n", encoding="utf-8")

    @property
    def entries(self) -> list[_Entry]:
        return list(self._entries)
